# vim:ft=kitty

## name: Lauds
## author: Joshua Blais
## license: GPL-3.0
## blurb: A muted, low-saturation light theme for kitty.

#: basic colors
foreground                      #1a1d21
background                      #f0efeb
selection_foreground            #f0efeb
selection_background            #b8b5b0

#: cursor
cursor                          #1a1d21
cursor_text_color               #f0efeb

#: url
url_color                       #4d6b6b

#: borders/bell
active_border_color             #4d6b6b
inactive_border_color           #d8d6d3
bell_border_color               #8b6666
visual_bell_color               none

#: tab bar
active_tab_foreground           #1a1d21
active_tab_background           #d8d6d3
inactive_tab_foreground         #7d7a75
inactive_tab_background         #e0dcd4
tab_bar_background              #f0efeb
tab_bar_margin_color            none

#: marks
mark1_foreground #f0efeb
mark1_background #4d6b6b
mark2_foreground #f0efeb
mark2_background #8b7e52
mark3_foreground #f0efeb
mark3_background #8b6666

#: the basic 16 colors

#: black
color0  #efeeed
color8  #7d7a75

#: red
color1  #8b6666
color9  #6f5252

#: green
color2  #5a6b5a
color10 #485648

#: yellow
color3  #8b7e52
color11 #6f6542

#: blue
color4  #5a6b7a
color12 #485662

#: magenta
color5  #6b5a6b
color13 #564856

#: cyan
color6  #64757d
color14 #505e64

#: white
color7  #4a4d51
color15 #1a1d21
